
namespace MyProject
{
    public struct Point 
    {
        public int X;
        public int Y; 
    }

    public class Order
    {
        public int OrderId;
        public string CustomerName;
        public int Quantity;
        public decimal UnitPrice;
        public decimal TotalPrice;
        public bool IsPaid;
        public double DiscountPercent;
        public string ShippingCity;
        public char Priority;
        public long ItemCode;

        public void CalculateTotal()
        {
            TotalPrice = Quantity * UnitPrice *
                         (decimal)(1 - DiscountPercent / 100);
        }

        public void PrintSummary()
        {
            Console.WriteLine(
                $"OrderId: {OrderId}, " +
                $"Customer: {CustomerName}, " +
                $"TotalPrice: {TotalPrice:F2}, " +
                $"IsPaid: {IsPaid}"
            );
        }
    }



    class Program
    {
        private static int fieldValue = 50;

        public static int FindSingleNumber(int[] nums)
        {
            int result = 0;

            foreach (int num in nums)
            {
                result ^= num;
            }

            return result;
        }

        static void Main()
        {
            #region Part _ A
            // ============================================================
            // Project Files Explanation
            // ============================================================
            //
            // .csproj:
            // This is the C# project file.
            // It contains project settings such as the target framework,
            // output type, nullable settings, implicit usings,
            // package references, and other build configurations.
            //
            // Program.cs:
            // This is the main C# source code file of the application.
            // It contains the program's entry point and the code that
            // starts and controls the application.
            //
            // obj/:
            // This folder contains intermediate files generated by the
            // .NET build process.
            // These files are used by the compiler and build system.
            // Developers normally do not edit these files manually.
            //
            // bin/:
            // This folder contains the final build output of the project,
            // such as the executable file, DLL files, and other files
            // required to run the application.
            //
            // ============================================================

            /*
            <Project Sdk="Microsoft.NET.Sdk">

              <PropertyGroup>
                <OutputType>Exe</OutputType>
                <TargetFramework>net10.0</TargetFramework>
                <ImplicitUsings>enable</ImplicitUsings>
                <Nullable>enable</Nullable>
              </PropertyGroup>

            </Project> 
            */

            /*
              File-scoped namespace is used to avoid an extra level of
              indentation because the namespace applies to the entire file.
              Therefore, we do not need curly braces around the namespace.
             */

            /*
             MyProject.slnx :-
             The project uses the newer .slnx solution format.
             The classic .sln format has the advantage of being widely
             supported by older Visual Studio and .NET tooling.
             */
            #endregion

            #region Part _ B
            // 1. Declare variables of different types

            int myInt = 10;
            long myLong = 100000L;
            double myDouble = 25.75;
            decimal myDecimal = 150.50m;
            bool myBool = true;
            char myChar = 'A';
            string myString = "Hello";
            var myVar = 42;

            Console.WriteLine("=== Variables and Runtime Types ===");

            Console.WriteLine($"int: {myInt}, Type: {myInt.GetType()}");
            Console.WriteLine($"long: {myLong}, Type: {myLong.GetType()}");
            Console.WriteLine($"double: {myDouble}, Type: {myDouble.GetType()}");
            Console.WriteLine($"decimal: {myDecimal}, Type: {myDecimal.GetType()}");
            Console.WriteLine($"bool: {myBool}, Type: {myBool.GetType()}");
            Console.WriteLine($"char: {myChar}, Type: {myChar.GetType()}");
            Console.WriteLine($"string: {myString}, Type: {myString.GetType()}");
            Console.WriteLine($"var: {myVar}, Type: {myVar.GetType()}");


            // 2. Implicit Conversion

            Console.WriteLine("\n=== Implicit Conversion ===");

            int number = 100;

            long convertedLong = number;

            char letter = 'A';
            int convertedInt = letter;

            Console.WriteLine($"int to long: {convertedLong}");
            Console.WriteLine($"char to int: {convertedInt}");


            // 3. Explicit Conversion

            Console.WriteLine("\n=== Explicit Conversion ===");

            double value = 10.75;

            int castResult = (int)value;

            int convertResult = Convert.ToInt32(value);

            Console.WriteLine($"(int) double: {castResult}");
            Console.WriteLine($"Convert.ToInt32: {convertResult}");


            // 4. Integer Division Trap

            Console.WriteLine("\n=== Integer Division ===");

            int intDivision = 5 / 2;
            double doubleDivision = 5.0 / 2;

            Console.WriteLine($"5 / 2 = {intDivision}");
            Console.WriteLine($"5.0 / 2 = {doubleDivision}");


            // 5. Boxing and Unboxing

            Console.WriteLine("\n=== Boxing and Unboxing ===");

            int originalNumber = 50;

            object boxedNumber = originalNumber;

            Console.WriteLine($"After boxing: {boxedNumber}");

            int unboxedNumber = (int)boxedNumber;

            Console.WriteLine($"After unboxing: {unboxedNumber}");


            // 6. Parsing

            Console.WriteLine("\n=== Parsing ===");

            string validString = "42";

            int parsedNumber = int.Parse(validString);

            Console.WriteLine($"int.Parse(\"42\"): {parsedNumber}");

            string badString = "abc";

            bool success = int.TryParse(badString, out int tryParsedNumber);

            Console.WriteLine($"TryParse(\"abc\") succeeded: {success}");

            if (success)
            {
                Console.WriteLine($"Parsed value: {tryParsedNumber}");
            }
            else
            {
                Console.WriteLine("Parsing failed. \"abc\" is not a valid integer.");
            }


            // 7. float to decimal

            Console.WriteLine("\n=== float to decimal ===");

            float floatValue = 25.5f;

            decimal decimalValue = (decimal)floatValue;

            Console.WriteLine($"float value: {floatValue}");
            Console.WriteLine($"decimal value: {decimalValue}");

            #endregion

            #region Part _ C
            Point p1 = new Point
            {
                X = 1,
                Y = 2
            };

            Point p2 = p1;

            p2.X = 99;

            Console.WriteLine("\nExperiment 1:");
            Console.WriteLine($"p1.X = {p1.X}");
            Console.WriteLine($"p2.X = {p2.X}");


            // Experiment 2: Class Reference

            Order o1 = new Order
            {
                OrderId = 1001,
                CustomerName = "Mohamed",
                Quantity = 3,
                UnitPrice = 250.00m,
                TotalPrice = 0m,
                IsPaid = false,
                DiscountPercent = 10.0,
                ShippingCity = "Mansoura",
                Priority = 'H',
                ItemCode = 9876543210L
            };

            o1.CalculateTotal();

            Order o2 = o1;

            o2.IsPaid = true;

            Console.WriteLine("\nExperiment 2:");
            Console.WriteLine($"o1.IsPaid = {o1.IsPaid}");
            Console.WriteLine($"o2.IsPaid = {o2.IsPaid}");


            // Experiment 3: Object

            object boxedOrder = o1;

            Order o3 = (Order)boxedOrder;

            Console.WriteLine("\nExperiment 3:");
            Console.WriteLine(
                $"ReferenceEquals(o1, o3) = {object.ReferenceEquals(o1, o3)}"
            );


            // Print Summary

            Console.WriteLine("\nOrder Summary:");

            o2.PrintSummary();


            // Final Explanation

            Console.WriteLine("\nFinal Explanation:");

            Console.WriteLine(
                "A struct is a value type, so assignment copies its values."
            );

            Console.WriteLine(
                "A class is a reference type, so assignment copies the reference."
            );

            Console.WriteLine(
                "The Order object is stored on the heap, while references point to it."
            );

            Console.WriteLine(
                "Storing a reference type in an object variable does not create a new object."
            );
            #endregion

            #region Part _ D
          
            Console.WriteLine("===== D1 - Scope =====");

            ReadField1();
            ReadField2();

            MethodScopeDemo();
            BlockScopeDemo();

            Console.WriteLine("\n===== D2 - Compound Assignment =====");

            CompoundAssignmentDemo();

            Console.WriteLine("\n===== D3 - Bitwise Operators =====");

            BitwiseDemo();
        }

        // Field can be accessed from different methods
        static void ReadField1()
        {
            Console.WriteLine("Field from Method 1: " + fieldValue);
        }

        static void ReadField2()
        {
            Console.WriteLine("Field from Method 2: " + fieldValue);
        }

        // Method Scope
        static void MethodScopeDemo()
        {
            int localValue = 100;

            Console.WriteLine("Local variable: " + localValue);
        }

        // Block Scope
        static void BlockScopeDemo()
        {
            for (int i = 0; i < 3; i++)
            {
                int insideLoop = i * 10;

                Console.WriteLine(
                    "i = " + i +
                    ", insideLoop = " + insideLoop);
            }
        }

        // D2 - Compound Assignment Operators
        static void CompoundAssignmentDemo()
        {
            int total = 100;

            total += 5;
            Console.WriteLine("total += 5  -> " + total);

            total -= 10;
            Console.WriteLine("total -= 10 -> " + total);

            total *= 2;
            Console.WriteLine("total *= 2  -> " + total);

            total /= 5;
            Console.WriteLine("total /= 5  -> " + total);

            total %= 7;
            Console.WriteLine("total %= 7  -> " + total);
        }

        // D3 - Bitwise Operators
        static void BitwiseDemo()
        {
            int a = 12;
            int b = 10;

            int andResult = a & b;

            int orResult = a | b;

            int xorResult = a ^ b;

            Console.WriteLine("a = " + a + " (1100)");
            Console.WriteLine("b = " + b + " (1010)");

            Console.WriteLine("a & b = " + andResult);
            Console.WriteLine("a | b = " + orResult);
            Console.WriteLine("a ^ b = " + xorResult);

        #endregion

            #region Part _ F
            int[] nums1 = { 4, 1, 2, 1, 2 };
            Console.WriteLine("Test 1: " + FindSingleNumber(nums1));

            // Test 2
            int[] nums2 = { 2, 2, 5, 5, 7 };
            Console.WriteLine("Test 2: " + FindSingleNumber(nums2));
            #endregion
        }
    }
}
